/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Format {
  PNG = 0,
  JPG = 1,
  JPEG = 2,
  WEBP = 3
}
export function createImage(len?: number | undefined | null, difficulty?: number | undefined | null, line?: boolean | undefined | null, noise?: boolean | undefined | null, format?: Format | undefined | null): Captcha
export class Captcha {
  text: string
  image: Uint8Array
}
